server: {port: 8084}
spring: {application: {name: legacy-service}}
eureka: {client: {serviceUrl: {defaultZone: http://localhost:8761/eureka/}}}
management: {endpoints: {web: {exposure: {include: health,info}}}}
